package com.ctbcbank.navi.mid.campaign.management.service.campaignform.createcoupontemplateform;

public interface CampaignFormCreateCouponTemplateFormService {
    CampaignFormCreateCouponTemplateFormRsBo createCouponTemplateForm(CampaignFormCreateCouponTemplateFormRqBo campaignFormCreateCouponTemplateFormRqBo);
}
