package com.ctbcbank.navi.mid.campaign.management.service.campaignform.querycoupontemplateform;

public interface CampaignFormQueryCouponTemplateFormService {
    CampaignFormQueryCouponTemplateFormRsBo queryCouponTemplateForm(CampaignFormQueryCouponTemplateFormRqBo campaignFormQueryCouponTemplateFormRqBo);
}
